apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: preciso-ingress
  namespace: preciso
spec:
  rules:
    - host: preciso.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: preciso-backend
                port:
                  number: 8000
