apiVersion: apps/v1
kind: Deployment
metadata:
  name: preciso-worker
  namespace: preciso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preciso-worker
  template:
    metadata:
      labels:
        app: preciso-worker
    spec:
      containers:
        - name: worker
          image: IMAGE_WORKER
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: preciso-config
            - secretRef:
                name: preciso-secrets
