apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakehouse-mlflow
  namespace: preciso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lakehouse-mlflow
  template:
    metadata:
      labels:
        app: lakehouse-mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.14.1
          args:
            - mlflow
            - server
            - --host
            - 0.0.0.0
            - --port
            - "5000"
            - --backend-store-uri
            - sqlite:///mlflow.db
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: lakehouse-mlflow
  namespace: preciso
spec:
  selector:
    app: lakehouse-mlflow
  ports:
    - port: 5000
      targetPort: 5000
