apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakehouse-unity-catalog
  namespace: preciso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lakehouse-unity-catalog
  template:
    metadata:
      labels:
        app: lakehouse-unity-catalog
    spec:
      containers:
        - name: unity-catalog
          image: unitycatalog/unitycatalog:latest
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: lakehouse-unity-catalog
  namespace: preciso
spec:
  selector:
    app: lakehouse-unity-catalog
  ports:
    - port: 8085
      targetPort: 8085
